version: '2'
services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mysql
    volumes:
      - /moedb:/var/lib/mysql
    ports:
      - "3306:3306"
  web:
    build: .
    command: bash -c "if [ -f /app/tmp/pids/server.pid ]; then rm /app/tmp/pids/server.pid; fi && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  mono_apps:
    build: ./mono_apps
    volumes:
      - .:/app
    depends_on:
      - db