version: '2'
services:
  db:
    image: mariadb
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=mysql
    volumes:
    - /moedb:/var/lib/mysql
  web:
    build: .
    command: bash -c "bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
     - "3000:3000"
    depends_on:
      - db
